### ISSUE TITLE
Not sure what this is

### ISSUE THREAD

**Issue by PineNappler** [adde88/besside-ng_pineapple#1]
Occasionally i get this
UNHANDLED MGMT 10cking [SSID] WPA - DEAUTH (know 2 clients)
it repeats for a bit then usually continues.

VERY useful tool :) thanks

**Comment by PineNappler** [comment]
Just had this message on trying to launch the latest 5ghz version
"./besside-ng: wi_open(): No child processes"
ran fine afterwards.

**Comment by adde88** [comment]
Yeah, i've encountered some strange error-messages like that some times.
I'm not sure what's the cause of it...
The solution seems to be trying again.
But i will be looking into it. :)

**Comment by adde88** [comment]
About the: UNHANDLED MGMT
It could be that besside-ng are seing some frames that it's unable to process, and then errors.
I'll be looking into it as well. :)

**Comment by PineNappler** [comment]
this one looks planned/anticipated but just in case i put it here.
"bad grab_hidden_ssid"
