### ISSUE TITLE
Is automated 5ghz support possible?

### ISSUE THREAD

**Issue by PineNappler** [adde88/besside-ng_pineapple#2]
It seems i can manually specify a 5ghz channel but during automated attack it only seems to scan 1-11.
I understand that most have both 2.4 & 5ghz running with the same password but some only run 5ghz networks. if not possible no worries just a "nice to have" thanks for your work as always

**Comment by adde88** [comment]
I can modify the source file to add 5GHz channels if wanted.
Or perhaps make it as an option.

**Comment by adde88** [comment]
Besside-ng will now automatically scan all 165 channels automatically.
Compared to the old 11 channels.
It's using approx. 250ms on each channel, so a complete scan could take about a minute to complete.

Files are now stored in in the /tmp folder
Example: /tmp/wpa.cap    /tmp/wep.cap   /tmp.besside.log

**Comment by PineNappler** [comment]
Thank you @adde88 , works great on a dual radio Tetra, but still tries to scan all channels when run on a 2.4 ghz only radio. Like you suggested maybe a -5ghz option would be best - if you tried to run on a nano there would be lots of time wasted scanning unreachable channels.

Options: -
2.4ghz only (default)
-5 = 5ghz only
-full = both 2.4 + 5ghz

**Comment by adde88** [comment]
Besside-ng will now automatically detect the channels that are available on the device being used.
